name: Merge dependency updates
on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "ORCA CI"

permissions:
  contents: write
  pull_requests: write

jobs:
  automerge:
    uses: acquia/cli/.github/workflows/automerge.yml@main
